import {
  Controller,
  Post,
  Body,
  Headers,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiHeader } from '@nestjs/swagger';
import { WebhookReceiverService, WebhookPayload } from './webhook-receiver.service';
import { WebhookProcessorService } from './webhook-processor.service';

@ApiTags('Webhooks')
@Controller('api/webhooks')
export class WebhooksController {
  constructor(
    private readonly receiverService: WebhookReceiverService,
    private readonly processorService: WebhookProcessorService,
  ) {}

  @Post()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Receive and process gateway webhook callbacks' })
  @ApiHeader({
    name: 'x-lera-box-signature',
    required: false,
    description: 'HMAC SHA256 signature generated by Gateway',
  })
  @ApiResponse({ status: 200, description: 'Webhook acknowledged and processed' })
  async handleWebhook(
    @Body() payload: WebhookPayload,
    @Headers('x-lera-box-signature') signature?: string,
  ) {
    const event = await this.receiverService.recordEvent(payload, signature);
    await this.processorService.processEvent(event);
    return { status: 'acknowledged', eventId: event.id };
  }
}
