import {
  Controller,
  Post,
  Body,
  Headers,
  HttpCode,
  HttpStatus,
  Req,
  UseGuards,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiHeader, ApiBearerAuth } from '@nestjs/swagger';
import { Request } from 'express';
import { AuthGuard } from '@nestjs/passport';
import { WebhookReceiverService, WebhookPayload } from './webhook-receiver.service';
import { WebhookProcessorService } from './webhook-processor.service';

interface RequestWithRawBody extends Request {
  rawBody?: Buffer;
}
@ApiTags('Webhooks')
@Controller('api/webhooks')
export class WebhooksController {
  constructor(
    private readonly receiverService: WebhookReceiverService,
    private readonly processorService: WebhookProcessorService,
  ) { }

  @Post()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Receive and process gateway webhook callbacks' })
  @ApiHeader({
    name: 'x-lera-box-signature',
    required: false,
    description: 'HMAC SHA256 signature generated by Gateway',
  })
  @ApiResponse({ status: 200, description: 'Webhook acknowledged and processed' })
  async handleWebhook(
    @Body() payload: WebhookPayload,
    @Req() req: RequestWithRawBody,
    @Headers('x-lera-box-signature') signature?: string,
  ) {
    const rawBody = req.rawBody;
    const event = await this.receiverService.recordEvent(payload, rawBody, signature);
    await this.processorService.processEvent(event);
    return { status: 'acknowledged', success: true, eventId: event.id };
  }

  @Post('setup')
  @UseGuards(AuthGuard('jwt'))
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Register the three mandated callback event types' })
  @ApiResponse({ status: 200, description: 'Callbacks registered successfully' })
  async setupWebhooks(
    @Req() req: Request & { user: { id: string } },
    @Body() body: { url: string },
  ) {
    return this.receiverService.registerAllWebhooks(req.user.id, body.url);
  }
}
